export const FETCH_ALL_FILMS_START = 'FETCH_ALL_FILMS_START';
export const FETCH_ALL_FILMS_FAILURE = 'FETCH_ALL_FILMS_FAILURE';
export const FETCH_ALL_FILMS_SUCCESS = 'FETCH_ALL_FILMS_SUCCESS';

export const POST_FILM_START = 'POST_FILM_START';
export const POST_FILM_FAILURE = 'POST_FILM_FAILURE';
export const POST_FILM_SUCCESS = 'POST_FILM_SUCCESS';

export const DELETE_FILM_START = 'DELETE_FILM_START';
export const DELETE_FILM_SUCCESS = 'DELETE_FILM_SUCCESS';
export const DELETE_FILM_FAILURE = 'DELETE_FILM_FAILURE';

export const GET_SORTED_FILMS_START = "GET_SORTED_FILMS_START";
export const GET_SORTED_FILMS_SUCCESS = "GET_SORTED_FILMS_SUCCESS";
export const GET_SORTED_FILMS_FAILURE = "GET_SORTED_FILMS_FAILURE";

export const GET_FILMS_BY_TITLE_START = "GET_FILMS_BY_TITLE_START";
export const GET_FILMS_BY_TITLE_SUCCESS = "GET_FILMS_BY_TITLE_SUCCESS";
export const GET_FILMS_BY_TITLE_FAILURE = "GET_FILMS_BY_TITLE_FAILURE";

export const GET_FILMS_BY_ACTOR_START = "GET_FILMS_BY_ACTOR_START";
export const GET_FILMS_BY_ACTOR_SUCCESS = "GET_FILMS_BY_ACTOR_SUCCESS";
export const GET_FILMS_BY_ACTOR_FAILURE = "GET_FILMS_BY_ACTOR_FAILURE";

export const POST_FILE_START = 'POST_FILE_START';
export const POST_FIlE_FAILURE = 'POST_FILE_FAILURE';
export const POST_FILE_SUCCESS = 'POST_FILE_SUCCESS';